/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public String getGreeting() {
        return "hello world!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public class Bitmap {
        
    }
}
