/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.nio.file.FileSystems;
import java.nio.file.Path;

public class App {
    public String getGreeting() {
        return "hello world!";
    }

    public static void main(String[] args) {
        // Find an image.
        Path imagePathName = FileSystems.getDefault().getPath("resources", "mario.bmp");

        // Read the image.
        Bitmap bmpDiagonally = new Bitmap(imagePathName);
    }

    public static class Bitmap {

        public Bitmap(Path imagePath) {
        }
    }
}
